name: Get Latest Tag - Smoke Test

on:
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run get-latest-tag-js action
        id: get_latest
        uses: ./.github/actions/get-latest-tag-js
        with:
          repo: shaneyboy/movies-client-static
          docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Show result (raw)
        run: |
          echo "result: ${{ steps.get_latest.outputs.result }}"

      - name: Show parsed fields
        run: |
          echo "ref: ${{ fromJSON(steps.get_latest.outputs.result).ref }}"
          echo "repository: ${{ fromJSON(steps.get_latest.outputs.result).repository }}"
          echo "tag: ${{ fromJSON(steps.get_latest.outputs.result).tag }}"
          echo "digest: ${{ fromJSON(steps.get_latest.outputs.result).digest }}"
