name: Test calculate-docker-tags
on:
  workflow_dispatch: {}

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build action
        working-directory: ./actions/calculate-docker-tags
        run: |
          set -e
          # npm ci requires a package-lock.json; fall back to npm install if missing
          npm ci || npm install
          npm run build

      - name: Run action
        id: run
        uses: ./actions/calculate-docker-tags
        with:
          image_name: ghcr.io/example-owner/example-repo

      - name: Show output
        run: |
          echo "Tags output from step: <<<<"  
          echo "${{ steps.run.outputs.tags }}"  
          echo ">>>>"

      - name: Assert tags
        run: |
          # Fail if output is empty
          if [ -z "${{ steps.run.outputs.tags }}" ]; then
            echo "No tags were produced by the action" >&2
            exit 1
          fi

          # Fail if 'latest' not present (adjust as needed for your expected tags)
          echo "${{ steps.run.outputs.tags }}" | grep -q "latest" || (
            echo "Expected 'latest' tag not found in action output" >&2
            exit 1
          )
